[project]
name = "course-ai-agents-homework-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.8.1",
    "requests>=2.32.5",
    "wikipedia>=1.4.0",
    "Unidecode>=1.3.7",
]
